### ISSUE TITLE
Profile set to null after linking address

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3955] opened 2023-05-18 20:13 UTC
## Description
May be related to #3479.

Steps to reproduce:
- Go to http://localhost:8080/redacted-cartel/discussion/3112-redacted-cartel-governance-community-forum-guidelines
- Log in with an address
- Add a new address
- Try clicking "view profile" (sometimes this works)
- Go back, select another address, then select the newly created address
- Try clicking "view profile" while having the new address selected (this should break)

## Acceptance Criteria
- View Profile should always link to your profile and not be null.

**Comment by CowMuon** [comment] 2023-05-25 18:22
@raykyri Are you able to reproduce?

**Comment by raykyri** [comment] 2023-05-25 19:07
Seems to be fixed now!

**Closed by raykyri** 2023-05-25 19:07 UTC
Labels: 🐛 bug, grab-n-go
