### ISSUE TITLE
Poll tag not being removed if poll is deleted

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3878] opened 2023-05-15 20:21 UTC
## Description
BD reported. Creating and then removing a poll does not remove the poll tag on a thread.

## Acceptance Criteria
- Deleting a poll should remove the poll tag from a thread.

**Comment by alexyoung23j** [comment] 2023-05-17 16:24
So I cannot reproduce this but I found a bug with poll deletion that was fixed instead.

**Comment by alexyoung23j** [comment] 2023-05-30 15:16
BD reported that this is NOT fixed despite being merged on 5/30. Reopening.

**Comment by jnaviask** [comment] 2023-05-31 19:07
Yes -- we should do a migration to rectify the database state in accordance with our contract (= has_poll means it has a poll).

**Closed** 2023-06-02 15:13 UTC
Labels: 🐛 bug, 3, BD Reported
