### ISSUE TITLE
Seven Polkadot JS modals pop up when first authorizing Commonwealth UI

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#911] opened 2020-10-22 19:43 UTC

**Comment by raykyri** [comment] 2020-12-15 21:35
This is probably the cause: https://github.com/hicommonwealth/commonwealth/issues/1003

**Comment by gdjohnson** [comment] 2020-12-16 00:46
#1011 merged; closing.

**Closed by gdjohnson** 2020-12-16 00:46 UTC
Labels: 2, bug, high priority
