### ISSUE TITLE
Decide on State Management 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2435] opened 2023-01-09 19:42 UTC
Mithril Class Components handle state by re-rendering when this variables are set.  React uses setState to schedule both class and functional components re-rendering. We, basically shove everything in app store. [1] 

We need to decide how we are going to handle state in the Interop layer and beyond, and document this clearly so anyone coming on can quickly ramp up without [resplunking](https://www.notion.so/hicommonwealth/CMN-Glossary-Resplunking). 

### Acceptance Criteria:

Documentation page in Notion that explains what our approach to state management in the newly Reactified app will be. actual acceptance criteria here is any FE dev can understand exactly how we will be handling state with just this doc.

@jnaviask / @mhmulford0 Pairing on this. 

[1] Hey! So we do have an app store

**Comment by jnaviask** [comment] 2023-01-10 18:11
Currently -- this works in the interop layer, via a Proxy that calls setState when we update a class property. This works for redraws, although it's less than ideal for long-term use. We will need to scope out the longer-term plans for how state management works.

**Comment by kurtisassad** [comment] 2023-02-10 21:06
State management has become a important piece of the puzzle for the large bundle sizes. Right now we code split on every view. The issue is that every view imports state.ts, and state.ts has a huge circular dependency tree:
![graph (1)](https://user-images.githubusercontent.com/14794654/218193611-3cdc54b6-5c53-48cd-9329-2ca8206b62e9.svg)

This results in the views not actually being split correctly, because after importing state, a large portion of the project is also loaded in due to circular dependency issues. Therefore we need some way to handle this. There are two options:
break the dependency from controller -> state, or break the dependency from state -> controller.

There are many libraries that do just that. The most popular of them is redux toolkit. In this framework the state is passed as component props through the react components. As a result the import dependency is only made at the top level component depend on state. This will break the direct dependency from controller -> state resolving many circular dependencies. Secondly the dependency from state -> controller is broken by the way it performs state updates. Instead of updating the state directly, it sends an event to update the state through "reducers".

So in this way the majority of the circular dependencies will be resolved (as long as the reducers do not depend on themselves). As a result I expect a large speed increase due to the code splitting actually being able to split the boundaries between views.

The downsides of using a state management framework like redux is that there is a little bit of a learning curve. Although redux toolkit is the most popular, some members of the team don't want to use it, so other suggestions are welcome. At the end of the day what is important is that we need to refactor our state.ts so that we don't have so many circular dependencies and can properly code split on views.

**Comment by jnaviask** [comment] 2023-05-11 20:15
We've landed on tanstack/query + zustand.

**Closed by jnaviask** 2023-05-11 20:15 UTC
Labels: post-react
