### ISSUE TITLE
Auto-Favorite/Star communities users join to the sidebar

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#7862] opened 2024-05-16 17:25 UTC
### Description

When a user joins a community have it auto-starred into their sidebar. This is the same "favoriting" feature that currently exists, we just want it to be automatic for when a user joins a community.

### Project Owner

@HIM92

### User Stories / Acceptance Criteria

As a user, I have just joined Common. I am a member of no communities when I join. I explore Common and join a new community. When I hit Join, the community automatically show up as favorited 

### Design Screenshot

This is how a community the user joins should look by default (using current functionality)

<img width="133" alt="Screenshot 2024-05-16 at 2 07 06 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/49603504-8045-4bcd-952f-62155c1ac7c4">
<img width="308" alt="Screenshot 2024-05-16 at 2 07 12 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/542f9090-314a-420e-95aa-8e263d50e9f3">

### Additional Context

Right now users can star any community on the sidebar that they choose. This change is just to automate the function so a user does not have to star the communities. 

If a user does not want a community starred/favorited then they can use the previous method to unfavorite.

**Comment by zakhap** [comment] 2024-05-16 17:51
Moreover, for all existing users, we should (1 time) auto-star all the communities they have joined; retroactive starring of existing community memberships. Users will be able to unstar using the existing sidebar flow.

**Comment by ForestMars** [comment] 2024-05-16 18:10
Duplicate of #7397

**Closed by ForestMars** 2024-05-16 18:10 UTC
Labels: enhancement, refinement, needs estimate
