### ISSUE TITLE
Admin action cards: Background shadows

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#6355] opened 2024-01-12 20:25 UTC
## Describe the bug

On Admin cards we have strange background shadow 
### Initial conditions

**Environment:** 
QA

**Branch/Release version:** 
Master/v0.9.1 tag

**Browser:** 
All

**Wallet:** 
All

## Reproduction steps

1. Go to: https://qa.commonwealth.im/
2. Sign in
3. Create new community 
4. Observe

## Actual behavior

On QA env behind admin cards we have strange background shadow

## Expected behavior

On PR video, those shadows are not visible
## Screenshots / Video

https://app.screencast.com/47AywkEmp3amw

**Comment by mzparacha** [comment] 2024-01-16 17:10
Not reproducible for me even on QA 

https://github.com/hicommonwealth/commonwealth/assets/51641047/a1f389b4-27a4-44b7-a53c-3f7ee7d2991c

cc: @ilijabojanovic

**Comment by CowMuon** [comment] 2024-01-16 17:16
Optimistically closing as `Can't Reproduce`- If it resurfaces as a problem, please reopen @ilijabojanovic

**Closed by CowMuon** 2024-01-16 17:16 UTC
Labels: 🐛 bug, 1
