### ISSUE TITLE
React: Responsive state update, thread content is cutoff at specific screensize

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#3422] opened 2023-04-12 17:36 UTC
![Image](https://user-images.githubusercontent.com/5334557/231538677-9ab62a13-a64b-414d-abb3-097dad34e438.png)

**Comment by jnaviask** [comment] 2023-04-12 17:40
Dupe of #3417

**Closed** 2023-04-12 17:40 UTC
Labels: 1, React
