### ISSUE TITLE
Admins & Mods / Topics not Loading for Common community

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#6418] opened 2024-01-22 17:37 UTC
## Describe the bug
Admins and topic page is not loading for the common community. 

## Reproduction steps
Go into the Common Protocol and click Admin and Mods or Topics on the sidebar. It is not loading correctly. 

## Expected behavior
Those pages should load

## Screenshots / Video
https://www.loom.com/share/5355bf4c853f45f28d85861b3f27f075?sid=2454bea3-e07c-4aa7-acbf-114b94b62f44

## Reporter
Growth Team

**Comment by jnaviask** [comment] 2024-01-22 17:40
Was caused by incorrect release of admin feature (enabled feature flag prematurely) -- resolved by disabling flag until work is completed.

**Closed by jnaviask** 2024-01-22 17:40 UTC
Labels: 🐛 bug, needs estimate
