### ISSUE TITLE
Updating thread stage causes page error

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4636] opened 2023-07-31 16:53 UTC
Steps to reproduce:

1. Change any stage on a thread
2. Immediately will see a page that shows "cannot read properties of null"

**Acceptance Criteria:**
Changing a thread topic should not lead to a broken page, and the topic should actually be changed without refreshing.

**Comment by jnaviask** [comment] 2023-07-31 17:25
Dupe of #4606

**Closed by jnaviask** 2023-07-31 17:25 UTC
Labels: 🐛 bug
