### ISSUE TITLE
🪣 Better DX Automation (GHA)

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#4258] opened 2023-06-15 13:14 UTC
## Description
We need @demoticbot to handle more of the housekeeping around our development process. As such, we have a punch list of actions needed. Please feel free to add additional suggestions in comments (anyone, not just assignee here.) 

- [ ] Tickets moving into status "in progress" must have point label (runs when any issue moved to in progress) 
- [ ] Moving to Boom  automatically closes issue (was working?)
- [x] PR's must have linked issue, or are automatically converted to draft (runs when PR opened)
- [x] Stale issues closed after extremely generous period (cf. [action gist](https://gist.github.com/CowMuon/90d0797765b70d4676f18a6a4399d998)) 
- [ ] Backlog tickets can only move to teed up (or no status) and not directly to in progress
- [ ] Only ENG leads should be teeing up. (Process note: anyone can request a story be teed up) 
- [ ] Only Issues should be allowed to be added to the project board (Do not allow PRs)

## Engineering Requirements
- Github Actions (GHA) should be added one at a time, each in its own PR 
- All added actions needs to be thoroughly tested so there are no surprises

## Acceptance Criteria
It does the thing. (Check off above as completed, until there are no more) 

## Additional Considerations 
Any actions that either check issues to see if they have an associated PR, or conversely checks PRs to see if they have an associated issue, should be able to safely and consistently handle corner and edge cases, such as PR closing multiple issues, or an issue that was not broken down, and so requires multiple PRs to close.

**Comment by kurtisassad** [comment] 2023-07-05 14:53
I think that we will need high level of permissions (Admin) In order to implement these. These will require limiting interactions, which can be found here:
https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository#limiting-interactions-in-your-repository

The issue is we need the settings button for the repo, but only repo admins are allowed to do this. As a result, for the time being I have marked this as blocked.

**Comment by kurtisassad** [comment] 2023-07-07 19:11
Taking out of blocked.

I will make a new repo, and go through the steps needed to be ran by the code owners. After I determine how to solve these bucket issues, I will make a list of these steps that a code owner can go through to finish off the ticket.

**Comment by kurtisassad** [comment] 2023-08-17 19:41
Figured out why I cannot trigger CI run on moved cards. The project must be created from enterprise edition (Needs to be a project repository board):
(Docs saying it needs to be project repository board):
https://docs.github.com/en/github-ae@latest/actions/managing-issues-and-pull-requests/removing-a-label-when-a-card-is-added-to-a-project-board-column#creating-the-workflow

(How to make project repository board):
https://docs.github.com/en/github-ae@latest/issues/organizing-your-work-with-project-boards/managing-project-boards/creating-a-project-board#creating-a-repository-project-board

**Comment by CowMuon** [comment] 2023-08-17 19:52
Boo Github!

**Comment by kurtisassad** [comment] 2023-08-17 19:54
Anyways I made a free trial enterprise account, so we can probably still be able to do this as long as whoever creates the project has access to our organization.

**Comment by kurtisassad** [comment] 2023-08-21 16:16
We also need to use github classic projects. The problem is I cannot test it because I cannot create a classic project in a repo in order to test it.

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#project_card

**Comment by jnaviask** [comment] 2023-08-22 20:45
@kurtisassad have you looked into https://github.com/marketplace/actions/automate-projects or similar solutions?

**Comment by kurtisassad** [comment] 2023-08-22 20:53
I have looked into it. I have:
- Tried it out, doesn't trigger on card move.
- Saw issue linked with someone running into the same issue as me https://github.com/takanabe/github-actions-automate-projects/issues/27

The problem is I think they also rely on classic projects. Its just that this action was [last updated in 2021](https://github.com/takanabe/github-actions-automate-projects), and github project classic was deprecated in 2022. This is why they don't mention it doesn't work with regular projects.

**Comment by jnaviask** [comment] 2023-09-29 20:04
cc @kurtisassad what is outstanding for this ticket? Would like to move it to C7 board but unsure of what blockers are / what is needed.

**Comment by kurtisassad** [comment] 2023-10-02 12:47
@jnaviask  The blockers to the remaining unchecked buckets items are that they require us to use project card actions, which require us to use github projects classic. This is a problem for me, because I cannot test classic projects, as you can only create them if you own a repo that was created before github projects classic was deprecated.

I cannot test on our repo because the code needs to be in the master branch for it to trigger on project card actions.

So although it is technically still possible, I feel like this blocker is too large for me to overcome (I cannot be certain code that I write will work correctly the first time).

**Closed** 2024-02-07 20:02 UTC
Labels: 5, 8, blocked, grab-n-go
