### ISSUE TITLE
BUG: 1inc community user has issues with log in

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5762] opened 2023-11-27 14:37 UTC
## Describe the bug

1inch user with profile id = 127667 can't log in on application.

## To Reproduce

No reproduction steps for now
## Expected behavior

User should be able to log in

**Comment by kurtisassad** [comment] 2023-11-27 17:46
Do we have any additional context here? Do we know which type of address they were trying to link?

**Comment by kurtisassad** [comment] 2023-11-28 15:39
I have been looking into it quite a bit. I have a doc I am using to collect my thoughts
https://docs.google.com/document/d/1GHGuIE6S7-4zqHmtgMbfuDZHanyv05E7KNPmmr5jHzs/edit?usp=sharing

Marking as 3 pointer for now because it is not easy to identify with the given information.

**Comment by kurtisassad** [comment] 2023-11-28 15:56
Figured out how to reproduce and part of the issue:
1. Go to some community, create account
2. Log out
3. Go to a different community, sign in there.

The result is that a new blank profile is created in step 3, and the address in step 1 is linked to it.

**Closed** 2023-11-28 19:52 UTC
Labels: 🐛 bug, 3
