### ISSUE TITLE
Profile threads tab gives "Failed to execute 'removeChild' on 'Node'" when coming from Osmosis community

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3619] opened 2023-04-26 21:10 UTC
## Description
BD reported. See video:
https://www.loom.com/share/10296a44e70b41398711dc00125e85f6

## Acceptance Criteria
- The threads tab should not crash when accessed after visiting a community.

**Comment by Miaplacidus** [comment] 2023-05-02 20:07
@jnaviask I'm unable to reproduce the error locally, so any fix I make cannot be confirmed either way. However, I have a possible solution that I've pushed that up to branch `3619-bug-child_node_removal_failure`. This solution assumes that the underlying error is due to React not being able to remove "child" elements of a fragment because fragments don't add anything to the page. It may be wrong, but anyone able to reproduce the error locally would be able to confirm.

**Comment by jnaviask** [comment] 2023-05-03 20:13
Thank you for the update @Miaplacidus!

**Comment by mhagel** [comment] 2023-05-11 22:19
I couldn't reproduce this today, just noting.

**Comment by CowMuon** [comment] 2023-05-26 20:46
Closing as can't reproduce.

**Closed** 2023-05-30 18:15 UTC
Labels: 🐛 bug, 2, grab-n-go, can't reproduce
