### ISSUE TITLE
Discord webhook links to comments are invalid

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3647] opened 2023-04-28 16:17 UTC
## Description
Stargaze discord webhook is generating links like https://commonwealth.im/stargaze/discussion/59795 -- which is invalid, as 59795 is presumably a comment id and not a thread id. See video for source: https://www.loom.com/share/071b064635af4ef5bcfec66c18f9bdee

Likely related to root_id removal.

## Acceptance Criteria
- Discord webhook should generate valid links to comments.

**Comment by alexyoung23j** [comment] 2023-04-28 18:45
Not reproducing locally, links that are sent to discord seem to work fine. Investigating.

**Comment by alexyoung23j** [comment] 2023-04-28 19:04
Appears this might have been fixed in #3637 - in `shared/utils`, `getThreadUrl` was changed to accept 2 params from accepting 3. `createComment` had been expecting 2, and so the missing third param, which was the actual comment id, was not getting appended. @kurtisassad does this sound right? Not sure if this was something you knew was impacted with your PR, I could be mistaken about this fix

**Comment by kurtisassad** [comment] 2023-04-28 19:43
Yes this looks to be the issue. Before cwUrl which was the url of the emitted notification was being set to have comment id instead of thread id due to the mismatch between the arguments and parameters of getThreadUrl.

**Comment by alexyoung23j** [comment] 2023-04-28 19:43
Closing as #3637 fixed the problem with getThreadUrl that was causing the broken webhooks. It will be fixed on prod when that PR is deployed.

**Closed by alexyoung23j** 2023-04-28 19:43 UTC
Labels: bug, 2, high priority
