### ISSUE TITLE
KSM CW Channel is refused a WebSocket Connection

### ISSUE THREAD

**Issue by thomivy** [hicommonwealth/commonwealth#331] opened 2020-06-08 17:17 UTC
## Description
```
WebSocket connection to 'ws://localhost:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
_init @ app.6f672b5d.js:62
app.6f672b5d.js:62 Websocket error Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
onerror @ app.6f672b5d.js:62
error (async)
_init @ app.6f672b5d.js:62
setTimeout (async)
onclose @ app.6f672b5d.js:62
app.6f672b5d.js:62 Websocket closed
```

## *Who* is the bug affecting?
Users attempting to interact with and not merely read the KSM section.

## *What* is affected by this bug?
Interactivity with the KSM chain

## *When* does this occur?
Upon entering the Discussion section of the channel, or any other section.

## *Where* on the platform does it happen?
KSM Channel

## *How* do we replicate the issue?
Click Kusama Channel

**Comment by drewstone** [comment] 2020-06-08 17:51
Potential solution:
- Change node URL from secure websocket to match others.

**Comment by thomivy** [comment] 2020-06-12 22:31
Currently unable to post to discussions or connect to KSM on CW. Title on posting remains inactive/unclickable and 'Setup required' shows on post button.

Console Errors:

`WebSocket connection to 'ws://localhost:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
_init @ app.1a840421.js:62
app.1a840421.js:62 Websocket error Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}`

**Comment by drewstone** [comment] 2020-06-12 23:26
Those websocket connections shouldn't be impacting connection to the chain, since they're localhost and not chain connecting ws.

Do you have other steps to reproduce?
- Browser type?
- Device?

I'm still able to get on Kusama atm, connecting fine.

**Comment by raykyri** [comment] 2020-06-13 04:24
@thomivy can you take a screenshot of the bug with the full browser window visible and put it on Slack?

I get a different error when I go to any Kusama page such as https://commonwealth.im/kusama/proposal/discussion/460-treasury-proposal-kusama-wallet is which is the API error and suggests we need to re-run a deploy.

![image](https://user-images.githubusercontent.com/1273926/84559762-62ed3f80-acf2-11ea-8b42-27a286523d8a.png)

**Comment by dillchen** [comment] 2020-06-16 22:56
We can close this issue, correct?

**Closed** 2020-06-16 22:56 UTC
Labels: bug
