### ISSUE TITLE
Forum Improvements: Sort Threads

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#3717] opened 2023-05-04 18:15 UTC
Stub ticket

- [Linked Notion Document](https://www.notion.so/buildcommon/Sort-Threads-cd0eaca2b83249ada7f2e20817ff5632?pvs=4)

**Comment by jnaviask** [comment] 2023-05-16 00:39
Dupe of #3821

**Closed by jnaviask** 2023-05-16 00:39 UTC
