### ISSUE TITLE
Image compression for community icon

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#4322] opened 2023-06-22 17:57 UTC
As a user, when I try to add an icon for my community during community creation, I get an error message asking me to upload a smaller image.

**Comment by sachben91** [comment] 2023-06-22 18:10
Related? https://github.com/hicommonwealth/commonwealth/issues/4238

**Comment by CowMuon** [comment] 2023-07-01 00:35
Closed as duplicate of #4238

**Closed by CowMuon** 2023-07-01 00:35 UTC
Labels: 🐛 bug, PA:create-community
