### ISSUE TITLE
Evmos incorrect tokenBalance (fka Admin unable to create a thread)

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4299] opened 2023-06-21 15:36 UTC
BD has reported that the admins in Evmos are unable to create a thread. Their balance is 0 on Common, (though it works on beta), so probably related to a token balance issue.

**Acceptance Criteria:**
Token balances should show correctly and evmos admin should be able to create threads.

**Comment by mhagel** [comment] 2023-06-26 18:38
Reporter's issue is resolved, but this may be the underlying issue:

>Their balance is showing as 0 because their evmos address is being resolved incorrectly after keplr 2.0 so we're looking up for a different address

**Comment by mhagel** [comment] 2023-06-27 21:48
Here's my understanding of the user's experience:

1. User signed up as Evmos admin with an `osmo` address pre-Keplr 2.0
    - (I may be wrong about this- maybe they used their `evmos` address before.)
2. After Keplr 2.0, when user logs into Evmos, Keplr assumes they want to use their `evmos` address to log in
3. (Unconfirmed): we believe at this step, Keplr resolved the evmos address incorrectly.
4. User reports that the tokenBalance query is using the "wrong" `evmos` address

**Comment by mhagel** [comment] 2023-06-27 22:59
Findings so far:

- BD confirmed the above understanding is correct, and also  
    - >In the top right profile drop down an incorrect evmos address is shown as well 
- When I join Evmos community with an `osmo` address, our tokenBalance query does indeed derive the wrong evmos address from my osmo address. 
- We don't have the ethermint logic in our server code to get the correct evmos address. This was happening before Keplr 2.0, and it has nothing to do with keplr.
- Our current logic takes the osmo address, converts it to evmos in a standard Cosmos bech32 way. However Evmos does this differently.

**Comment by mhagel** [comment] 2023-06-27 23:21
Some guesses about what is happening.

1. Before Keplr 2.0, user was able to log in to /evmos with "Osmosis" selected in Keplr. 
2. Keplr 2.0 forces user to log in with the **correct** evmos address that is associated with the osmo address they used to be able to log in to /evmos with. This evmos address has no tokens.
    a. In Keplr 1.0 this was the equivalent of selecting "Evmos" chain before logging in.
    b. User never did this. They always selected "Osmosis" in Keplr before login.
3. By default, user is now logged in to /evmos with evmos address they never use. 
    a. Still need to investigate something: in our DB, the user's evmos address they reported as "wrong" is an evmos admin.
5. User used Unified Profiles function to associate account with their usual `osmo` address
6. After logging in, user switches to their usual `osmo` address to do admin stuff on /evmos
7. The tokenBalance query then uses our incorrect logic to query the incorrectly-derived `evmos` address
    a. this was always happening before, so I don't know how they experienced no problem until Keplr 2.0.
8. If user sent some EVMOS tokens to their `evmos...` address that is associated with their usual `osmo...`address, and logged in with that, they would get the correct tokenBalance query.

Even if 8 is correct, we still need to fix the address-derviation for ethermint accounts in our back-end.

**Comment by mhagel** [comment] 2023-06-27 23:21
@RhysCommonwealth If you want to follow along, you can look at my comments above and feel free to chime in here.

**Comment by mhagel** [comment] 2023-06-28 21:37
After more investigation today, I see the primary bug here is looking up the wrong `evmos` address associated with a particular `osmo` or any other cosmos address. PR above addresses this.

- There is still a mysterious incorrect evmos address associated with the reporter's account. I have decided to ignore this because the reporter told us they were able to connect the correct evmos address when they log into /evmos
- Until somebody else reports this, we can assume the reporter added this wrong address to CW (without their knowledge) during a brief time when Keplr was deriving evmos addresses incorrectly, or it could have been caused by another event specific to Evmos. This extra address is not harmful or blocking, since the user has their real evmos address connected to their profile now.

**Comment by mhagel** [comment] 2023-06-29 16:24
>There is still a mysterious incorrect evmos address associated with the reporter's account. 

Note that this mysterious address was added December 2022. So it existed before Keplr 2.0. Just more evidence that it is not a new thing.

**Comment by CowMuon** [comment] 2023-06-29 21:11
While we could easily make this into something more complicated, is the most straightforward solution here to fix the bad (legacy) data, and not the current logic that the legacy k1 addresses are breaking/not compatible with? 

How many users total are being affected? It seems like they could just use a different address? What are the main downsides here (in addition to those users being so inconvenienced, and having to communicate that to them effectively.) 

@mhagel Let's discuss what the best solution path here is.

**Comment by mhagel** [comment] 2023-06-29 21:32
>How many users total are being affected? 

Unknown, but it may be resolving itself when users log in to /evmos with Keplr 2.0. CW may not recognize their (correct) address and ask them to create a new account or link to an existing one. Once they do, their problem is solved.

>is the most straightforward solution here to fix the bad (legacy) data, and not the current logic that the legacy k1 addresses are breaking/not compatible with?

Maybe. The only people that will continue to be affected are those who specifically log into a non-evmos community every time, then switch to /evmos. They may continue to incorrectly see tokenBalance = 0 .

@CowMuon

**Comment by mhagel** [comment] 2023-06-29 22:00
>is the most straightforward solution here to fix the bad (legacy) data?

We wouldn't realistically be able to fix data ourselves. But users can by just logging in to /evmos.


>What are the main downsides here

- We could possibly run into more cases where our back-end logic isn't sufficient for chains that derive addresses differently from the standard. 

- We may continue to hear about unxpected "tokenBalance = 0" cases, from users who for example:
    - _always_ log into /osmosis, then go to /evmos  


---

I should probably note some thoughts here. This is related but applies beyond the scope of this ticket:

Keplr 2.0 changed the way users log in to CW. Before, you had to have a chain selected in Keplr. If I remember correctly, that chain would determine the address used to log in. 

Now, You cannot highlight a chain. Keplr chooses the right chain for you.

The impact to our users is that they may have to associate more addresses to their Profiles as they log into different communities. Luckily, Unified Profiles makes this possible. Power-users may be annoyed that they have to gather all their addresses into a single account, unless they follow the same login path every time. 

We can't really unscramble this egg, but luckily, we have the systems in place to handle multiple addresses.

@CowMuon

**Comment by CowMuon** [comment] 2023-06-29 23:09
btw, this is exactly the kind of thing to discuss during proto office hours (ie a future facing architectural decision, not a thing-we-have-to-ship-today) which we have moved to Tuesdays at 12:30 ET (ie following Tuesday standup)

**Comment by CowMuon** [comment] 2023-06-29 23:12
> Power-users may be annoyed that they have to gather all their addresses into a single account, unless they follow the same login path every time.

Yeah, obvi that could be a PITA for some of them, anything beyond that would just be guessing. 

> We can't really unscramble this egg, but luckily, we have the systems in place to handle multiple addresses

This is really (at) the heart of one of the main discussions we are having, namely our Common (mental) model of what a user is, and what an address is, in the context of Web 3 vs. Web 2. Too much there to unpack in this comment, so just to highlight, but this is something we absolutely need to get right at the model level, that can't simply be "_fixed in code._"

**Comment by mhagel** [comment] 2023-07-03 19:10
Remaining questions:

- Are users experiencing tokenBalance = 0? Are they Evmos users? Need to check logs.
- Have any other users experienced similar problems?
- Should we do any data modifications (delete bad addresses)?

**Comment by CowMuon** [comment] 2023-07-03 21:28
Confirmed closed by Growth Team.

**Closed by CowMuon** 2023-07-03 21:28 UTC
Labels: 🐛 bug, 3, BD Reported
