### ISSUE TITLE
Redesign "Select account to Join" modal when joining a community 

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#9555] opened 2024-10-15 20:39 UTC
## Describe the bug
List of addresses to select from is not visually appealing when joining a community. 

Link to new design:

https://www.figma.com/design/dGPiswtnIfQIzSNOlB4MNC/Sticky-editor-%2B-Sidebar-%2B-Thread-UI?node-id=717-4384&t=h908TOKN6cMlp0An-1

**Comment by cowballzach** [comment] 2024-10-15 20:39
low priority p4. LMK if more context is needed.

**Comment by Israellund** [comment] 2024-10-21 14:52
@salman-neslit Assigning this to you for this week, it is one of Growth's priorities. Please let me know if you can't access the Figma link and I can let you in.

**Comment by salman-neslit** [comment] 2024-10-29 22:05
@sssssabinaaa I wanted to reach out for clarification regarding the "Set Default" button functionality in the new UI.

Could you please provide more details on how this feature is intended to work? Specifically, I’m interested in understanding its expected behavior, any related conditions.

**Comment by Israellund** [comment] 2024-10-30 19:37
@sachben91 In order to set a default a new value needs to be stored in the database, and a migration will also most likely need to happen. Can you confirm that setting the default address, as seen in the Figma designs, is the correct functionality to implement for this ticket?

**Closed** 2024-11-05 14:22 UTC
Labels: bug, 1, 2
