### ISSUE TITLE
Spinning Cow After signing in through Magic 

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#6415] opened 2024-01-22 16:39 UTC
## Describe the bug
Infinite loading cow after Mark signs in through Magic. 

### Initial conditions
He's on a mac and is using chrome to sign in through magic. 

## Reproduction steps
Sign in through magic *note that eng is having a hard time recreating now*

## Screenshots / Video
https://www.loom.com/share/3b2b64d76a7444dca343d8334c548e07?sid=0c11b6ed-6fc9-440c-83c9-2dde7b8464ac
<img width="328" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/144931524/c96a2590-deb8-45e7-b5a8-63f11d580f8d">

## Reporter

growth team

**Comment by mzparacha** [comment] 2024-02-05 18:26
Not reproducible locally.

**Comment by jnaviask** [comment] 2024-02-05 21:10
Main issue here is it never prompts for token signature -- user should see another magic pop-up asking to sign a session key.

**Comment by jnaviask** [comment] 2024-02-05 21:25
Bug occurs on homepage login specifically.

**Comment by jnaviask** [comment] 2024-02-05 21:32
Affected user was asked to sign in with browser extensions disabled, and was able to successfully sign in. List of extensions installed:
![image](https://github.com/hicommonwealth/commonwealth/assets/1860629/447724f1-a608-46db-a13e-e99b34f5cb68)

**Comment by jnaviask** [comment] 2024-02-05 21:36
Was unable to reproduce from installing these extensions -- RC still unknown.

**Comment by jnaviask** [comment] 2024-02-05 21:40
Had affected user remove XDEFI wallet and login was successful.

**Comment by jnaviask** [comment] 2024-02-05 21:47
Reproduced by installing XDEFI and configuring a wallet.

**Comment by jnaviask** [comment] 2024-02-05 21:53
Closing for #6589

**Closed by jnaviask** 2024-02-05 21:53 UTC
Labels: 🐛 bug, P1, needs estimate
