### ISSUE TITLE
Add CSS on Tables generated from MD on View Thread Page

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5215] opened 2023-10-02 17:46 UTC
## Describe the bug

Our standard CSS is not being applied anymore to the tables rendered on the View Thread page. ~~This results in a terrible experience for more thorough and thought through posts, which are why people come to Common.~~

## To Reproduce

https://commonwealth.im/juno/discussion/13332-juno-charter

## Expected behavior

Table has standard styling as detailed in: https://www.figma.com/file/5iXtMFaRJopRNAe6nDCnP6/Forum-Experience-Improvements?type=design&node-id=187-22218&mode=design&t=LgUTokNCwwz2iRn5-0

## Additional context

Important note: for table overflow, sufficiently large tables via MD, should _internally scroll_ rather than overflowing on the X axis!

<img width="621" alt="Screen Shot 2024-01-08 at 9 26 32 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/36fce278-0ea3-467a-997e-9bfda1f87df6">

**Comment by Miaplacidus** [comment] 2024-01-08 16:47
@jessmart1213 @zakhap 
Markdown-generated tables currently have the default Markdown styling and I'm not seeing any indication in the code that there is supposed to be additional styling. Hence this question: Is there a Figma doc somewhere that contains the new/additional styling for tables generated from Markdown? 

Thanks for your help!

**Comment by jessmart1213** [comment] 2024-01-08 16:55
Hi @Miaplacidus! I believe the new styling can be found in Figma file [Forum Experience Improvements](https://www.figma.com/file/5iXtMFaRJopRNAe6nDCnP6/Forum-Experience-Improvements?type=design&node-id=187%3A22218&mode=design&t=48UicFshxxDi5skZ-1). But will leave to @zakhap to confirm. I also think there should be some updated tickets for this.

**Comment by Miaplacidus** [comment] 2024-01-08 17:25
@jnaviask @CowMuon 
@zakhap is currently working on updating this card to reflect that it is a feature request not a bug fix. Will begin work on it when he's done. 
Thanks, @zakhap!

**Comment by Miaplacidus** [comment] 2024-01-11 17:42
@ForestMars @jnaviask 
Correction to statement during standup: All of the table styling was completed as part of #6035, which has been merged into master already. That card, however, did not include the ask in the description above for internal scrolling on the table, which is the only work this card will call for given then previously completed work.

**Closed** 2024-02-28 15:53 UTC
Labels: 1
