### ISSUE TITLE
Create and delete comment slow to respond

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3523] opened 2023-04-19 20:16 UTC
## Description
BD reported. See video:
https://www.loom.com/share/4a95d8629bc747458aed0895a0fcfd0c

Need to track down root cause. Could be related to notification generation. May want to switch to an optimistic display.

## Acceptance Criteria
- Creating and deleting comments should feel fast.

**Comment by alexyoung23j** [comment] 2023-04-27 15:39
Unable to recreate slow creation, able to recreate slow deletion.

**Comment by alexyoung23j** [comment] 2023-04-27 16:18
Proving difficult to recreate locally- potentially related to slow deletion of Subscriptions though when reproducing on prod there were only 2 subscriptions to delete and the route still took 10 seconds to resolve.

**Comment by alexyoung23j** [comment] 2023-04-27 17:29
I am not able to reproduce this under any circumstances on local. However, my best guess right now is that removing the await on line 69 in `deleteComment.ts` would probably resolve the issues. But unable to confirm that at the moment.

**Comment by CowMuon** [comment] 2023-04-28 18:45
Please use Frick/Frack to recreate creation bug. Work with Mark to confirm. 

On the delete side, what the solution here?  @alexyoung23j

**Comment by alexyoung23j** [comment] 2023-04-28 19:14
Cannot recreate slow create comment on prod, frick/frack, or local. Whatever the problem was, it appears to have been resolved by some change that went in post video recording. 

Cannot recreate slow delete on local, but I can on prod and frick/frack. My strong suspicion is that its simply a matter of removing the await on line 69 in `createComment`, which I can test on frick/frack.

**Comment by alexyoung23j** [comment] 2023-04-28 19:49
Tested that fix on frick, works.

**Closed** 2023-05-10 18:34 UTC
Labels: enhancement, 2, React, grab-n-go, Performance
