### ISSUE TITLE
Fix ERC20 and 721 Create Community

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#3886] opened 2023-05-15 21:26 UTC
## Description
- Users are unable to create ERC 20 and 721 communities on Commonwealth. The form unnecessarily errors out because address, id, and name are not being passed to the `createChain` request

## Acceptance Criteria
- Form works as expected, and id, address, and name are passed in

Relevant context from Slack (https://commonxyz.slack.com/archives/C051XFN57FT/p1684183960316189)

**Comment by jnaviask** [comment] 2023-05-15 21:26
Dupe of #3885

**Closed by jnaviask** 2023-05-15 21:26 UTC
