### ISSUE TITLE
ASCII breaks formatting 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#5941] opened 2023-12-11 21:55 UTC
## Describe the bug
Pasting ASCII "destroys" it (left aligns & isn't monotype) 

## To Reproduce
Steps to reproduce needed here? @jnaviask 

## Expected behavior
Pasting ASCII text into editor works as expected? 

## Additional context
What guarantees does editor make around ASCII art? Is it something we support? Should user expect it to be properly formatted?

**Comment by CowMuon** [comment] 2023-12-11 21:55
@zakhap for ASCII art question.

**Comment by CowMuon** [comment] 2023-12-12 19:25
In code blocks that are more than one line do not display in monotype and are incorrectly aligned.

**Comment by lzach83** [comment] 2024-01-23 21:23
In order to get this correctly aligned, On Paste of ASCII Art it will convert to markdown and works as intended.

**Comment by lzach83** [comment] 2024-01-24 16:36
Because of the discovery on #5940 I have to rethink how this will work, originally I was using Regex to convert to code-block, however; it looks for "art" patterns like "---" or "//\\" and with the pasting of HackMD and Tables in general they use the same pattern.

**Comment by CowMuon** [comment] 2024-01-26 03:36
We should add a comment here to memorialize decision from conversation today, namely that we will not try to detect ascii art to put in a code block (tho I like the idea in principle- the less we make the user do, the more they like us) but rather will rely on the user knowing ASCII art needs to go into a code block. 

Subsequent to our call I spoke with Design about this just to confirm the approach; we agreed if you are posting ASCII art in web3, it's on you to know it prolly goes in a code block.

**Comment by lzach83** [comment] 2024-01-29 22:27
This is finished from this commit: https://github.com/hicommonwealth/commonwealth/pull/6375/commits/0ece9a083c8faf500a99c59417cf6b88f40e7499

**Comment by jnaviask** [comment] 2024-02-09 16:51
Determined won't fix as rich text being deprecated.

**Closed by jnaviask** 2024-02-09 16:51 UTC
Labels: 🐛 bug, 3, P3, external
