### ISSUE TITLE
Better Analytics Dashboard 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2580] opened 2023-01-27 19:58 UTC
Analytics Dashboard Improvements needed (Community/Admin facing) 

- [ ] Clean Up analytics dashboard page
- [ ] Better batched columns
- [ ] Load time 
- [ ] Most active users
- [ ] For Each Topic, show comments, threads by day, week, month.
- [ ] Weekly Email with (Forum and Gov Section) 
- [ ] Analytics API 

(Sprint 6) 
pair: @affordances

**Comment by jnaviask** [comment] 2023-05-11 19:57
Dupe of #2857

**Closed by jnaviask** 2023-05-11 19:57 UTC
Labels: C1, S5, BD
