### ISSUE TITLE
Bug: Polkadot auth is broken

### ISSUE THREAD

**Issue by mzparacha** [hicommonwealth/commonwealth#8848] opened 2024-08-14 19:03 UTC
## Describe the bug

Polkadot auth is broken for new and existing accounts.

For new accounts it fails with this error on the `/updateUser` API
```
[
    {
        "error": {
            "message": "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"number\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"id\"\n    ],\n    \"message\": \"Required\"\n  }\n]",
            "code": -32600,
            "data": {
                "code": "BAD_REQUEST",
                "httpStatus": 400,
                "path": "user.updateUser"
            }
        }
    }
]
```

and for existing accounts, it fails with this error on `/verifyAddress` route
```
{"status":400,"error":"Invalid signature, please re-register"}
```

### Initial conditions

**Environment:** 
Prod
**Branch/Release version:** 

**Browser:** 
All
**Wallet:** 
Polkadot -- didn't test with other wallets

## Reproduction steps
1. Try creating a new account on common with polkdot -- notice the issue
2. If you have an existing account, try logging in -- notice the issue

## Actual behavior
Polkadot auth is broken

## Expected behavior
Polkadot login should work

## Screenshots / Video
N/A

## Reporter
@mzparacha 

## Additional context
N/A

**Comment by jnaviask** [comment] 2024-08-14 19:08
Dupe of #8728

**Closed by jnaviask** 2024-08-14 19:08 UTC
Labels: bug, needs estimate
