### ISSUE TITLE
Forum Improvement: Show when a post has been edited

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#3715] opened 2023-05-04 18:11 UTC
This ticket needs acceptance criteria, and specification

Reference Document
- [Notion](https://www.notion.so/buildcommon/Show-when-a-post-has-been-edited-fbe87dabe30d4dff945654a35646b71d?pvs=4)

**Comment by jnaviask** [comment] 2023-05-05 21:33
Dupe of #3616

**Closed by jnaviask** 2023-05-05 21:33 UTC
