### ISSUE TITLE
Feature: User should claim token with magic wallet

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5525] opened 2023-10-31 20:05 UTC
## Description

1. User created a profile in Commonwealth using magic login
2. Community airdropped token to all of the addresses that are members of their Commonwealth community
3. Token was airdropped to the user's magic address
4. User is unable to access the airdrop since they don't have any access or control over their magic address

## Acceptance Criteria

When user sign up with magic wallet he should be able to to claim community token award.

**Comment by dillchen** [comment] 2023-10-31 20:11
related to #5072 and #5309

**Comment by mw2000** [comment] 2023-11-03 08:18
Addressed in standup call, duplicate work to what @ianrowan is tackling

**Comment by jnaviask** [comment] 2023-11-03 15:22
Dupe of #5072

**Closed as not planned by jnaviask** 2023-11-03 15:22 UTC
Labels: enhancement, needs estimate
