### ISSUE TITLE
Only query chains/nodes as needed rather than eagerly

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4976] opened 2023-09-06 19:41 UTC
## Description

Following #4973, we want to avoid eagerly loading every chain = community when the application loads, and instead only load the chains/chainnodes required for whatever page we're on. The references to the eagerly loaded data can be found via `app.config.chains` and `app.config.nodes`. Ideally we can totally deprecate these two variables.

## Engineering Requirements

- app.config.chains and app.config.nodes no longer used.
- chain data no longer fetched eagerly at app startup.

### Sub-Tickets:

See related suggestions in https://github.com/hicommonwealth/commonwealth/issues/4976#issuecomment-2269659183

A & C. [Add filter params and pagination to GET /communities endpoint](https://github.com/hicommonwealth/commonwealth/issues/8756) and https://github.com/hicommonwealth/commonwealth/issues/2617
B. [Add TRPC endpoint for GET /community/:id](https://github.com/hicommonwealth/commonwealth/issues/8755) and [Implement GET /community/:id in frontend](https://github.com/hicommonwealth/commonwealth/issues/8762)
D. [Add ?trending=true param to GET /communities to get the "Trending Communities" for dashboard page.](https://github.com/hicommonwealth/commonwealth/issues/8760)
E. [Update user.starredCommunities from /status response to include specific community data](https://github.com/hicommonwealth/commonwealth/issues/8753#top)

**Comment by jnaviask** [comment] 2023-09-06 21:50
@mzparacha note that we might need to improve the flexibility of our routes to support all the use cases involved. Feel free to loop in @rbennettcw if you need those routes modified (or you can do it yourself).

**Comment by mzparacha** [comment] 2023-09-07 13:10
Sure, thanks for the headsup.

**Comment by mzparacha** [comment] 2023-09-11 16:00
Any changes to the chain loader will affect some UI/pages which is not a big problem but it will also affect these important logical areas
- Authentication (wallet login, social login, address linking, and related features)
- App initialization flow (the `scopeMatchesChain` branch case in the Layout file)

Since we will be loading chains/nodes when needed, how should we deal with the loading state? We can do a simple await but it will mostly show a blank page or maybe a loader (depending on the situation)

**Comment by jnaviask** [comment] 2023-09-11 16:27
Can you get a list of problematic instances -- some of the values aren't necessary for us to query against app.config.

**Comment by mzparacha** [comment] 2023-09-11 16:39
Sure, just a heads up, even tho the nodes/chains API is independent now. In the front end the [`chains` depend on the `nodes` response](https://github.com/hicommonwealth/commonwealth/blob/d12e83fdd3eaa84a978d6f8c066078b229df93ca/packages/commonwealth/client/scripts/state/index.ts#L231-L244), so we can think of them as a single entity i.e `app.config.chains` is the main entity here.

The problematic instances is mostly in controllers ex:

- [1 - web wallets usage of app.config.chains](https://github.com/hicommonwealth/commonwealth/blob/704aaf033aa735e88ca55adfc046990b75dec63c/packages/commonwealth/client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts#L92-L98), 
- [2 - any use of `app.config.chains` in `app/login.ts`](https://github.com/hicommonwealth/commonwealth/blob/98a323a9362c73c7ee70655ef4a35845ee61f8ba/packages/commonwealth/client/scripts/controllers/app/login.ts#L254) 
- [3 - user.ts -> selectChain](https://github.com/hicommonwealth/commonwealth/blob/d12e83fdd3eaa84a978d6f8c066078b229df93ca/packages/commonwealth/client/scripts/controllers/server/user.ts#L258-L268)

and these non controllers

- [4 - chain helper selectChain](https://github.com/hicommonwealth/commonwealth/blob/14e80936df3511339331ff824682cceee5da787b/packages/commonwealth/client/scripts/helpers/chain.ts#L26-L32)
- [5- in useWallets](https://github.com/hicommonwealth/commonwealth/blob/623daf10851a911bd06c38ce1985e3a5dc71baa7/packages/commonwealth/client/scripts/hooks/useWallets.tsx#L127)

there are some more. Recap, the problem is how should we handle loading state when we load chain/nodes independently/non-eagerly from /status call.

cc: @jnaviask

**Comment by mzparacha** [comment] 2023-09-11 16:41
Backlogging this based on discussion @jnaviask

**Comment by jnaviask** [comment] 2023-09-11 16:45
Re above:
Case 1: this is the active chain, we should have the data
Case 2: this is a set of known defaults, no need to query the data from the backend
Case 3: this call sets the user default -- we don't need all the data, although we may need to rework the controller
Case 4: again, it uses a known default, so we can avoid a backend query
Case 5: don't understand why we need ALL COMMUNITIES ON THE PLATFORM to initialize wallets...

**Comment by CowMuon** [comment] 2024-01-08 21:38
Malik to coordinate with Protocol team when this gets teed up.

**Comment by mzparacha** [comment] 2024-08-05 18:28
Went over the existing usage for `app.config.chains/communities` and `/nodes`. Sharing thoughts/findings below

## Instances where its used and {insert} reason of usage
In most places, `app.config.chains` is used, either to get a specific detail/key about the community or the full community info (see [this](https://github.com/hicommonwealth/commonwealth/blob/b1fe460c100e70db9c5f716c4a39bc60364f2d62/packages/commonwealth/client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts#L102-L104) and [this](https://github.com/hicommonwealth/commonwealth/blob/d0e5f2cd3548fbc09b9c74dd7483cdce0db703f3/packages/commonwealth/client/scripts/helpers/chain.ts#L31-L42)) and `/nodes` is only called once on app init and that's for adding the `ChainInfo` data to each community in `app.config.chains` (see [here](https://github.com/hicommonwealth/commonwealth/blob/41b2c84ae2cbc4d13f0b62d72937da33f7a3b09e/packages/commonwealth/client/scripts/state/index.ts#L167-L200)).

Other than that there are some more usecases with "custom" logic/algos implemented directly in frontend, which can be refactored/moved to api as part of the optimization.

1. on communities page, we display all the communities filterable with "community tags", "base chain" and "stake enabled/disabled". The filters are applied directly in frontend as no api params to support the filters/pagination, data comes from `/communities?active=true`  which returns the full list of active community -- ref: https://github.com/hicommonwealth/commonwealth/blob/41b2c84ae2cbc4d13f0b62d72937da33f7a3b09e/packages/commonwealth/client/scripts/views/pages/communities.tsx#L195-L196
https://github.com/hicommonwealth/commonwealth/blob/41b2c84ae2cbc4d13f0b62d72937da33f7a3b09e/packages/commonwealth/client/scripts/views/pages/communities.tsx#L126

2. on dashboard page, we display `3` trending communities (can be `x`) which are calculated like this -> "User joined communities with new content first" + "Communities with higher monthly active thread count sorted by desc", this algo is currently implemented in frontend using data from `/communities?active=true` -- ref:
https://github.com/hicommonwealth/commonwealth/blob/41b2c84ae2cbc4d13f0b62d72937da33f7a3b09e/packages/commonwealth/client/scripts/views/pages/user_dashboard/TrendingCommunitiesPreview/TrendingCommunitiesPreview.tsx#L14-L16

3. on the community sidebar, we display "user-starred communities", the `/status` response includes the ids/timestamps for `user.starredCommunities` but excludes some other info ex: `icon URL, name` for community etc, which we get from mapping `app.config.chains`
https://github.com/hicommonwealth/commonwealth/blob/b1fe460c100e70db9c5f716c4a39bc60364f2d62/packages/commonwealth/client/scripts/views/components/sidebar/sidebar_quick_switcher.tsx#L30-L45


## Suggestions
- We add `ChainNode` to each community info from the `/communities` response (possibly with a param indicating that the response should include `ChainNode` or not) -- and in the frontend we call the endpoint only on communities list page.
- We add a new endpoint to "get" a specific community info with `ChainNode` (possibly with a param indicating that the response should include `ChainNode` or not) -- and in the frontend we call the endpoint only in instances where we need data of a specific community.
- For `1`, we add params to filter/paginate communities from `/communities` -- and in the frontend we call the endpoint only on communities list page.
- For `2`, we add `?trending=true` to `/communities` or something else to get the "trending communities" that implements the algo defined in `2` -- and in the frontend we call the endpoint only on dashboard page.
- For `3`, we update `/status` to return `user.starredCommunities` to return communities with at least this info `id, name, redirect, icon_url`

---

Sry for the wall of text, I tried to include all use-cases I found (not sure if I missed any).  Plz lmk your thoughts.

cc: @timolegros @jnaviask

**Comment by jnaviask** [comment] 2024-08-05 18:39
@mzparacha Wrt nodes: we expect the nodes list will scale FAR more slowly than the communities list, as new nodes are added extremely infrequently. So let's focus our effort on the communities piece. I think your last 3 suggestions for dealing with the specific cases are solid and we should pursue immediately -- feel free to ticket separately, or to use this ticket to handle them together if they're easy/quick. We will leave ChainNodes to deal with later.

**Comment by mzparacha** [comment] 2024-08-05 18:46
Thanks, i will start on the last 3 (will make separate tickets)
> - For 1, we add params to filter/paginate communities from /communities -- and in the frontend we call the endpoint only on communities list page.
> - For 2, we add ?trending=true to /communities or something else to get the "trending communities" that implements the algo defined in 2 -- and in the frontend we call the endpoint only on dashboard page.
> - For 3, we update /status to return user.starredCommunities to return communities with at least this info id, name, redirect, icon_url


but I think the main performance/optimization will come from the 2nd suggestion

> We add a new endpoint to "get" a specific community info with ChainNode (possibly with a param indicating that the response should include ChainNode or not) -- and in the frontend we call the endpoint only in instances where we need data of a specific community.

this way we can stop calling `/communities` on app load and only call it in the communities list page.

cc: @jnaviask

**Comment by jnaviask** [comment] 2024-08-05 18:47
@mzparacha we should likely use the standard GET pattern to allow querying single communities... cc @rbennettcw

**Comment by timolegros** [comment] 2024-08-05 18:51
@jnaviask @mzparacha if we are going to need to rewrite some routes/logic for this should we just transition to using trpc API? Could write trpc Queries to address changes in about 3 points. I suggest @mzparacha join the platform office hours on August 6th so we can see if this would be viable.

**Comment by mzparacha** [comment] 2024-08-05 19:12
Tickets: 

See related suggestions in https://github.com/hicommonwealth/commonwealth/issues/4976#issuecomment-2269659183

A. TODO
B. https://github.com/hicommonwealth/commonwealth/issues/8755
C. TODO
D. TODO
E. https://github.com/hicommonwealth/commonwealth/issues/8753

**Comment by mzparacha** [comment] 2024-08-26 13:17
The suggested changes are implemented in all sub-tickets. Closing as completed.

**Closed by mzparacha** 2024-08-26 13:17 UTC
Labels: enhancement, S1, S5, bucket 🪣
