### ISSUE TITLE
Gating: CW20 and CW721 support

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#5306] opened 2023-10-13 19:53 UTC
## Description

Add cw20 and cw721 tokens as gating options

## Additional context

(To be fleshed out)

**Comment by mhagel** [comment] 2023-10-13 19:54
@zakhap please fill in details as you see fit

**Comment by CowMuon** [comment] 2023-10-25 18:17
Closed as dupe of #5438

**Closed by CowMuon** 2023-10-25 18:17 UTC
Labels: enhancement, needs spec, PA:gating, needs estimate, Cosmos
