### ISSUE TITLE
Join community bug

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#8572] opened 2024-07-23 19:27 UTC
When attempting to join a community, an error is thrown in the console and the UI fails to update. After refreshing the page, the UI reflects that the community was joined.

Reproduced on: QA

![Image](https://github.com/user-attachments/assets/39444d2a-31bb-4235-8080-4222964c1f08)

## Acceptance Criteria
- Joining a community should update the UI without errors

**Comment by ForestMars** [comment] 2024-07-23 19:39
Nice catch Ryan. I actually joined a Community earlier today and didn't notice this behavior. Imma slap a low pri on it tho, we def have bigger 🐠 to fry

**Comment by Rotorsoft** [comment] 2024-07-29 14:57
@rbennettcw this has been fixed here - https://github.com/hicommonwealth/commonwealth/pull/8613

Can you confirm?

**Comment by mzparacha** [comment] 2024-07-29 16:12
closing https://github.com/hicommonwealth/commonwealth/issues/8587 as that seems like a duplicate of this one.

**Comment by rbennettcw** [comment] 2024-07-29 17:20
@Rotorsoft yep, it's fixed now

**Closed** 2024-07-29 17:20 UTC
Labels: bug, low priority, needs estimate
