### ISSUE TITLE
Visual Bug: Notifications Popover renders in wrong spot

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4481] opened 2023-07-12 18:08 UTC
## Description

If you click the notification bell to open the notifications popover prior to the page finishing loading, it opens in the top left corner, rather than the expected spot directly beneath the bell icon.

<img width="1512" alt="Screen Shot 2023-07-12 at 2 05 37 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/2ea84afc-8e57-4631-a91d-a81a8d9f948b">

## Acceptance Criteria

- Regardless of how quickly a user presses the notification bell icon to open the notifications popover, the notifications popover should show up in the expected location directly beneath the bell.

Expected behavior:
<img width="1512" alt="Screen Shot 2023-07-12 at 2 08 27 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/4f4a440f-229f-4bff-b467-d5817ecf6643">

**Comment by alexyoung23j** [comment] 2023-08-18 20:43
Unable to reproduce @zakhap you mind trying once again? might have been resolved with the new skeleton loader.

**Comment by jnaviask** [comment] 2023-09-01 18:08
Backlogged until repro confirmed.

**Comment by jnaviask** [comment] 2023-09-01 18:42
@zakhap cannot reproduce. Closing.

**Closed by jnaviask** 2023-09-01 18:42 UTC
Labels: 🐛 bug, grab-n-go, refinement
