### ISSUE TITLE
CopyPasta 3/3:  Pasting from IDE

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#5945] opened 2023-12-11 22:33 UTC
## Describe the bug
Ticket 2/3 for pasting other formats into markdown editor → from IDE 

## Expected behavior
Pasting Notion formatted data into markdown editor works as expected, is tested and confirmed for the following: 
- VS Code
- JetBrains / Webstorm
- VIM
- emacs 

## Acceptance criteria 
Pasting rich text formatted data from any of above listed IDEs: (or similar)
- Renders text correctly formatted 
- Cursor is rendered at end of pasted content, not beginning. 
- Return and all other functions work as normal 

## Additional context
It's not totally clear _why_ users are editing posts in a **code** editor, but it is currently not working for pasting such content in.

**Comment by lzach83** [comment] 2024-01-19 15:26
In a small holding pattern on this ticket till I get some sort of loom / video on how to reproduce.

**Comment by lzach83** [comment] 2024-01-23 22:08
Closing this ticket since it's no longer needed.

**Closed by lzach83** 2024-01-23 22:08 UTC
Labels: 🐛 bug, 1, P2, external
