### ISSUE TITLE
BUG: Proposals are not visible in sidebar for some communities

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5502] opened 2023-10-30 16:15 UTC
## Describe the bug

ENV: Production 
Branch: Master

When we visit some comos communities, proposal's are not visible in left side bar

## To Reproduce

1. Go to https://commonwealth.im/sentinel/proposals
2. Sign up with Keplr wallet 
3. Observe 

## Expected behavior

Proposals are not visible in left side bar.

## Additional context

Image:
https://app.screencast.com/DRObveUNr8XxO

**Comment by CowMuon** [comment] 2023-11-01 18:38
Dupe of #5447 (which has a [PR](https://github.com/hicommonwealth/commonwealth/pull/5507))

**Closed by CowMuon** 2023-11-01 18:38 UTC
Labels: 🐛 bug, needs estimate
