### ISSUE TITLE
Notifications: Broken comments url's on subscriptions page

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#8810] opened 2024-08-08 21:32 UTC
## Describe the bug

On notifications page, when user click on any comment, he will be redirected to the 404 page

### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

master/release/v1.5.4-x

**Browser:** 

All
**Wallet:** 

All
## Reproduction steps

1. Go to https://qa.commonwealth.im/
2. Sing in 
3. Go to notifications settings
4. Navigate on subscriptions tab
5. Click on comment

## Actual behavior

Redirection on 404 page. Seems our routing is broken. 
`https://qa.commonwealth.im/ilija/discussion/87816-notif?comment=87816` 

## Expected behavior

Open discussion with focus on comments

## Screenshots / Video

https://app.screencast.com/T28CXkLHB5czA

**Comment by burtonator** [comment] 2024-08-12 23:17
@ilijabojanovic I think this isn't a real bug.  Could you delete your existing subscriptions, re-create them, then try again? 

I can't reproduce this and all the URLs I'm creating work fine. Even on qa...

**Comment by burtonator** [comment] 2024-08-16 19:42
This is a duplicate of a bug that's already closed.

**Closed by burtonator** 2024-08-16 19:42 UTC
Labels: bug, 1
