### ISSUE TITLE
Wallet Connect login not working

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#5048] opened 2023-09-11 22:43 UTC
### Environment 
- Chrome on Desktop 
- Safari on Ios

### Steps to reproduce 

- Click login with Wallet Connect on desktop
- Finish the signing process on your phone on metamask
- Exit out of the sign in modal on the desktop and check if you are logged in 
- Refresh the page to see if login happens 

[Loom](https://www.loom.com/share/7e736809e24f48d787bdb007b6c047d3)

### Expected Results 
Logged into Common using Wallet Connect after clicking out of the sign in box or after refresh 

### Actual Results
Not logged into Common using Wallet Connect after clicking out of sign in after completing signing process on the phone and not logged in on refresh either 

### Priority for launch 
blocking the launch since this login flow is not working at all

**Comment by masvelio** [comment] 2023-09-12 14:14
Reproduced locally and on frack. It works correctly on beta or prod. First thing is that maybe we need to whitelist frack or [localhost](http://localhost/) to make walletconnect working? 

Other thing is that our backend throws error when I try to use metamask wallet on from my phone.

```
2023-09-12 16:05:33,890 INFO [verifySessionSignature.ts] Eth verification failed for 0x067a7910789f214A13E195a025F881E9B59C4D76: Error: Invalid signature: signature did not match /^(.+)\/([A-Za-z0-9]+)\/(0x[A-Fa-f0-9]+)$/
    at verifySessionSignature (/Users/marcin/Desktop/Projects/commonwealth/packages/commonwealth/server/util/verifySessionSignature.ts:255:15)
    at processAddress (/Users/marcin/Desktop/Projects/commonwealth/packages/commonwealth/server/routes/verifyAddress.ts:77:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at verifyAddress (/Users/marcin/Desktop/Projects/commonwealth/packages/commonwealth/server/routes/verifyAddress.ts:217:3)
2023-09-12 16:05:33,895 WARN [verifyAddress.ts] Failed to verify signature for 0x067a7910789f214A13E195a025F881E9B59C4D76: AppError: Invalid signature, please re-register
    at processAddress (/Users/marcin/Desktop/Projects/commonwealth/packages/commonwealth/server/routes/verifyAddress.ts:89:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at verifyAddress (/Users/marcin/Desktop/Projects/commonwealth/packages/commonwealth/server/routes/verifyAddress.ts:217:3)
e AppError: Invalid signature, please re-register
    at processAddress (/Users/marcin/Desktop/Projects/commonwealth/packages/commonwealth/server/routes/verifyAddress.ts:89:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at verifyAddress (/Users/marcin/Desktop/Projects/commonwealth/packages/commonwealth/server/routes/verifyAddress.ts:217:3) {
  status: 400
}
```

![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/c993c154-6ab7-4b38-b772-e6abf4ded159)

Would love @raykyri to take a look on this. 
cc @jnaviask @MuonShot

**Comment by kurtisassad** [comment] 2023-09-12 17:47
Issue is in verifySessionSignature.ts here:
```
      const signaturePattern = /^(.+)\/([A-Za-z0-9]+)\/(0x[A-Fa-f0-9]+)$/;
```
This pattern does not match valid ethereum addresses. For example, after logging in with walletconnect the signature passed is:
`0xc7ddf3a5c5b57eeaf36ad331c33a40154b1e8d6c5331c4164442d8b1979f65ad46dda2723cff4b38b5a46648804aff7ecd835b433cf7404d4372dcded95053261b`

On a regex tester, this pattern doesn't match this string. Possible solution, remove the stuff at the beggining:
```
      const signaturePattern = /^(0x[A-Fa-f0-9]+)$/;
```
But it might break whatever the earlier part of the regex was for

**Comment by raykyri** [comment] 2023-09-13 06:35
Fixed the WalletConnect issue, looks like it's working both on desktop and mobile including on Frack.

**Comment by masvelio** [comment] 2023-09-13 11:14
fixed with this commit https://github.com/hicommonwealth/commonwealth/pull/3426/commits/a9936eaaa2fcb6f6c0e3a440f1f05c2a6a5efc2a

**Closed** 2023-09-15 10:25 UTC
Labels: Session Keys
