### ISSUE TITLE
getLinks should not require JWT to query links on a proposal

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#9083] opened 2024-08-30 15:22 UTC
## Description

See: https://commonwealth.im/juno/proposal/354-juno-upgrade-v24 -- note the Unauthorized response in the network column. Could be related to #9023 but TBD

**Comment by timolegros** [comment] 2024-08-30 16:36
This is a duplicate of https://github.com/hicommonwealth/commonwealth/issues/4789

**Closed** 2024-08-30 17:37 UTC
Labels: bug, 1
