### ISSUE TITLE
Metamask wallet login erroring out on Brave browser

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#5970] opened 2023-12-12 16:21 UTC
## Describe the bug

The login process via Metamask wallet and other connected wallets creates errors due to different reasons. The collection of bugs ultimately creates different issues for the login flow.

The ultimate issue is if there is a wallet already connected to our Dapp but there is an issue that comes up for every scenario in case the connecting wallet and creating account have any problem/interruption.

## To Reproduce
1) Connect a wallet but does not finish the creation of the wallet causes the following error:
  - No profile data found for address 0x23f525258559E16C634eDF4093323CdbD2C4fd15 on-chain Ethereum
  - "Invalid Ethereum address: commonwealth.im wants you to sign in with your Ethereum account:
          0x23f525258559E16C634eDF4093323CdbD2C4fd15
          
          
          URI: https://commonwealth.im
          Version: 1
          Chain ID: 1
          Nonce: fqEumnHlsILH3wj4u
          Issued At: 2023-12-12T18:43:27.072Z
          Expiration Time: 2023-12-13T18:43:27.072Z
          Resources:
          - ethereum:0x069bd4CBB30aA6Ef1288091499D3FE23624A73fa:/commonwealth"

- The flow over here is fixed when you disconnect your wallet from the Dapp. 

**So the first issue is:** When someone connects their wallet to our Dapp but does not fully create an account or connect it to an account as a secondary address, we receive this issue.
- We should create a flow for addresses that are connected to our system but do not have fully settled accounts with us.

2) If the user clicks login and then clicks coin base wallet but waits more than around 30 seconds before signing the connection signature request, the wallet connects to our Dapp however our create a new user or add to existing account flows do not come up and ultimately causes the issue above.

## Additional context
- The error does not come up when you have a fresh installation of Brave browser with only Metamask installed.
- The error does not come up when you have a fresh installation of Brave browser with both Coinbase and Metamask wallet installed. It also provides the needed election of the wallet process.
- The error stops when you use the same wallets and set up with incognito mode.
- - All errors mentioned by @RhysCommonwealth can be resolved by logging into the wallet and disconnecting the wallet from the Commonwealth Dapp

Supersedes #5629

**Comment by egetekiner** [comment] 2023-12-12 19:23
in addition to that, the same issues come up with Chrome web browser. Probably during the error creation, the needed standards for recreating the error did not happen with the chrome browser so we thought it only happened with the brave browser. It is a general issue with out flow.

**Comment by ianrowan** [comment] 2023-12-12 21:19
This issue will be fixed with the coinbase wallet option: #5982 

Root cause is mismatched parameter for `personal_sign` similar to the #5845 1inch sign in issue. After breaking it out into its own controller this is fixed.

**Comment by egetekiner** [comment] 2023-12-13 21:24
I just maded the needed checks for login processes for the following usecase scenarios:

1) Only Metamask enabled
2) Metamask + Coinbase wallet enabled
3) Metamask + Coinbase + Phantom enabled

As @ianrowan said, the issue has been resolved with #5982 

I am closing this issue with this tests and upgrade.

**Closed by egetekiner** 2023-12-13 21:24 UTC
Labels: 🐛 bug, needs estimate
